### ISSUE TITLE
Translation completed

### ISSUE THREAD

**Issue by Blathroat** [claire-west/svstudio-manual-zh#1]
Hello,claire.

I've already finished translating it into Chinese. Thank you for your support. I think whether or not the image is translated has little impact on understanding. Because the position of windows and buttons in SynthV has no change. So I didn't translate the images at last. 

I find that SynthV 1.10 version is comming soon. I can translate the update after you updated the English version. Please ping me after you finished this update.

By the way, if you don't mind, I may promote it on Chinese video websites (Bilibili, just like Youtube) next. And there may be more traffic and user feedback. I'll collect and summarize these information and provide feedback to you.

**Comment by cv4x** [comment]
That's great, thanks for your efforts!

> By the way, if you don't mind, I may promote it on Chinese video websites

Yes, feel free to do so.

I'll let you know once I have the 1.10.0 changes ready. I usually only apply the changes once the final update is ready (not during the beta), because Dreamtonics might change things based on user feedback.
