### ISSUE TITLE
Changes for 1.10.0

### ISSUE THREAD

**Issue by cv4x** [claire-west/svstudio-manual-zh#2]
Hi @Blathroat , the changes for 1.10.0 have been committed to the English repository. I've already added all the new images to this repository as well.

Here is the full list of changes:

https://github.com/claire-west/svstudio-manual/commit/0b1d579ab34dee92bdc6c7b042c79a0078eaf95d

**Comment by Blathroat** [comment]
Hi @claire-west , I've already finish the translation for the 1.10.0 update.Thank you for ping me.
